apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: modcluster
  labels:
    app: modcluster
    context: AKSDemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: modcluster
        context: AKSDemo
    spec:
      containers:
        - name: modcluster
          image: yoichikawasaki/mod_cluster-dockerhub:0.0.2
          env:
            - name: MODCLUSTER_NET
              value: "192.168. 172. 10."
            - name: MODCLUSTER_PORT
              value: "80"
          ports:
            -  containerPort: 80
