apiVersion: apps/v1beta1  # apps/v1 for versions from 1.9.0, use apps/v1beta1 for before 1.9.0
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres
    context: AKSDemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: "postgres"
        context: AKSDemo
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: ticketmonster
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: userPassword
          ports:
            - name: postgres-port
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata

